cd /data/NCATS_ifx/data/WES/ && GATK -m 15g BaseRecalibrator -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT01/CT01_dedup.bam -knownSites /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz -knownSites /fdb/GATK_resource_bundle/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz -o CT01/CT01_recal_data.table -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK PrintReads -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT01/CT01_dedup.bam -BQSR CT01/CT01_recal_data.table -o CT01/CT01_recal.bam -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g BaseRecalibrator -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT02/CT02_dedup.bam -knownSites /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz -knownSites /fdb/GATK_resource_bundle/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz -o CT02/CT02_recal_data.table -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK PrintReads -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT02/CT02_dedup.bam -BQSR CT02/CT02_recal_data.table -o CT02/CT02_recal.bam -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g BaseRecalibrator -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT03/CT03_dedup.bam -knownSites /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz -knownSites /fdb/GATK_resource_bundle/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz -o CT03/CT03_recal_data.table -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK PrintReads -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT03/CT03_dedup.bam -BQSR CT03/CT03_recal_data.table -o CT03/CT03_recal.bam -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g BaseRecalibrator -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT04/CT04_dedup.bam -knownSites /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz -knownSites /fdb/GATK_resource_bundle/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz -o CT04/CT04_recal_data.table -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK PrintReads -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT04/CT04_dedup.bam -BQSR CT04/CT04_recal_data.table -o CT04/CT04_recal.bam -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g BaseRecalibrator -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT05/CT05_dedup.bam -knownSites /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz -knownSites /fdb/GATK_resource_bundle/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz -o CT05/CT05_recal_data.table -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK PrintReads -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT05/CT05_dedup.bam -BQSR CT05/CT05_recal_data.table -o CT05/CT05_recal.bam -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g BaseRecalibrator -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT06/CT06_dedup.bam -knownSites /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz -knownSites /fdb/GATK_resource_bundle/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz -o CT06/CT06_recal_data.table -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK PrintReads -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT06/CT06_dedup.bam -BQSR CT06/CT06_recal_data.table -o CT06/CT06_recal.bam -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed
