cd /data/NCATS_ifx/data/WES/ && GATK -m 20g IndelRealigner -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT01/CT01_dedup.bam -targetIntervals CT01/CT01_realignment_targets.list -o CT01/CT01_realigned_reads.bam && GATK -m 20g HaplotypeCaller -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT01/CT01_realigned_reads.bam -o vcf/CT01_raw_variants.vcf --genotyping_mode DISCOVERY -stand_call_conf 30 --dbsnp /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz

cd /data/NCATS_ifx/data/WES/ && GATK -m 20g IndelRealigner -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT02/CT02_dedup.bam -targetIntervals CT02/CT02_realignment_targets.list -o CT02/CT02_realigned_reads.bam && GATK -m 20g HaplotypeCaller -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT02/CT02_realigned_reads.bam -o vcf/CT02_raw_variants.vcf --genotyping_mode DISCOVERY -stand_call_conf 30 --dbsnp /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz

cd /data/NCATS_ifx/data/WES/ && GATK -m 20g IndelRealigner -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT03/CT03_dedup.bam -targetIntervals CT03/CT03_realignment_targets.list -o CT03/CT03_realigned_reads.bam && GATK -m 20g HaplotypeCaller -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT03/CT03_realigned_reads.bam -o vcf/CT03_raw_variants.vcf --genotyping_mode DISCOVERY -stand_call_conf 30 --dbsnp /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz

cd /data/NCATS_ifx/data/WES/ && GATK -m 20g IndelRealigner -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT04/CT04_dedup.bam -targetIntervals CT04/CT04_realignment_targets.list -o CT04/CT04_realigned_reads.bam && GATK -m 20g HaplotypeCaller -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT04/CT04_realigned_reads.bam -o vcf/CT04_raw_variants.vcf --genotyping_mode DISCOVERY -stand_call_conf 30 --dbsnp /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz

cd /data/NCATS_ifx/data/WES/ && GATK -m 20g IndelRealigner -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT05/CT05_dedup.bam -targetIntervals CT05/CT05_realignment_targets.list -o CT05/CT05_realigned_reads.bam && GATK -m 20g HaplotypeCaller -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT05/CT05_realigned_reads.bam -o vcf/CT05_raw_variants.vcf --genotyping_mode DISCOVERY -stand_call_conf 30 --dbsnp /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz

cd /data/NCATS_ifx/data/WES/ && GATK -m 20g IndelRealigner -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT06/CT06_dedup.bam -targetIntervals CT06/CT06_realignment_targets.list -o CT06/CT06_realigned_reads.bam && GATK -m 20g HaplotypeCaller -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -I CT06/CT06_realigned_reads.bam -o vcf/CT06_raw_variants.vcf --genotyping_mode DISCOVERY -stand_call_conf 30 --dbsnp /fdb/GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz
