cd /data/NCATS_ifx/data/WES/ && GATK -m 15g SelectVariants -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT01_raw_variants.vcf -selectType SNP -o vcf/CT01_SNP_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK -m 15g -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT01_raw_variants.vcf -selectType INDEL -o vcf/CT01_INDEL_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g SelectVariants -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT02_raw_variants.vcf -selectType SNP -o vcf/CT02_SNP_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK -m 15g -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT02_raw_variants.vcf -selectType INDEL -o vcf/CT02_INDEL_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g SelectVariants -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT03_raw_variants.vcf -selectType SNP -o vcf/CT03_SNP_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK -m 15g -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT03_raw_variants.vcf -selectType INDEL -o vcf/CT03_INDEL_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g SelectVariants -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT04_raw_variants.vcf -selectType SNP -o vcf/CT04_SNP_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK -m 15g -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT04_raw_variants.vcf -selectType INDEL -o vcf/CT04_INDEL_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g SelectVariants -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT05_raw_variants.vcf -selectType SNP -o vcf/CT05_SNP_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK -m 15g -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT05_raw_variants.vcf -selectType INDEL -o vcf/CT05_INDEL_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

cd /data/NCATS_ifx/data/WES/ && GATK -m 15g SelectVariants -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT06_raw_variants.vcf -selectType SNP -o vcf/CT06_SNP_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed && GATK -m 15g -R /fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta -V vcf/CT06_raw_variants.vcf -selectType INDEL -o vcf/CT06_INDEL_raw.vcf -L /data/NCATS_ifx/data/WES/hglft_genome_subset.bed

